import localFont from 'next/font/local'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '../components/Header'
import { Inter, Montserrat } from 'next/font/google'
import Loading from './loading'
import { Suspense } from 'react'

const montserrat = Montserrat({
 subsets: ['latin'],
 variable: '--font-montserrat',
 weight: ['100', '200', '800', '900'],
})

const geistSans = localFont({
 src: './fonts/GeistVF.woff',
 variable: '--font-geist-sans',
 weight: '100 900',
})
const geistMono = localFont({
 src: './fonts/GeistMonoVF.woff',
 variable: '--font-geist-mono',
 weight: '100 900',
})

export const metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 return (
  <ClerkProvider afterSignOutUrl='/'>
   <html lang='en'>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
     <Header />
     <Suspense fallback={<Loading />}>{children}</Suspense>
    </body>
   </html>
  </ClerkProvider>
 )
}
